### ISSUE TITLE
set gfxpayload=keep keep issue

### ISSUE THREAD

**Issue by b1g334** [vasi/rEFInd#1]
Where would I put the equivalent of "press e" at the grub menu as shown below

set gfxpayload=keep
outb 0x728 1
outb 0x710 2
outb 0x740 2
outb 0x750 0
and  i915.lvds_channel_mode=2 i915.modeset=1 i915.lvds_use_ssc=0
and after "quiet splash" i915.lvds_channel_mode=2 i915.modeset=1 i915.lvds_use_ssc=0 

This is the only way I can get the Ubuntu boot USB to disable the discreet AMD graphics and allow me to install to the 2nd disk. Once installed successfully (confirmed with the tambourine drum roll in Ubuntu) I get the same problem in rEFInd. 

Black screen.

I suspect this will be resolved after I install the proprietary AMD drivers... Which I can't do without some form of display.

**Comment by vasi** [comment]
Hey, I'm not actually the developer of rEFInd. This repo is just for my patches. You should go talk to Rod Smith: http://www.rodsbooks.com/refind/

**Comment by b1g334** [comment]
Oups, many thanks and sorry. Too many tabs open.
